<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UploadCSVRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'csv_file' => 'required|file|mimes:csv,txt'
        ];
    }

    public function messages()
    {
        return parent::messages() + [
                'mimes' => 'Тип файла должен быть формата .CSV',
                'required' => 'Поле с выбором файла обязательно для заполнения'
            ]; // TODO: Change the autogenerated stub
    }
}
